# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_about', models.CharField(max_length=512)),
                ('service_url', models.URLField(blank=True, null=True, unique=True)),
                ('service_file', models.FileField(upload_to=b'')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
