# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64, unique=True)),
                ('service_about', models.CharField(max_length=512)),
                ('service_url', models.URLField(blank=True, help_text='This link should be unique', null=True, unique=True)),
                ('service_msg', models.CharField(blank=True, default='We tried caling you. AMUA Clinic', help_text='Optional message to be sent', max_length=160, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
