# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anc_number', models.SlugField(max_length=6)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('patient_contact', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter number in this format +2547209XXXXX', max_length=13)),
                ('patient_name', models.CharField(max_length=64)),
                ('national_id', models.BigIntegerField(default=None, unique=True)),
                ('last_menstrual_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
