# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment_response',
            old_name='reminder',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='appointment_response',
            name='response_date',
            field=models.DateField(),
        ),
    ]
